// Generated by scripts/generate_rust_coefficients.py. Do not edit by hand.
//! Pose-only degree-16 coefficients for the fixed CRB15000 geometry.
//!
//! Coefficients are returned in ascending powers of tan(q6 / 2). DH constants
//! remain exact rationals until rounded at the requested MPFR precision.
use rug::Float;

/// Evaluate coefficients from [C·C, C·xd, C·yd, Cz, xd_z, yd_z].
#[allow(clippy::double_parens, unused_parens)]
pub fn coefficients_from_invariants(values: &[Float; 6], precision: u32) -> Vec<Float> {
    let [c2, cx, cy, cz, xz, yz] = values;
    let constant_0 = ((Float::with_val(precision, (-(12321_i64)))) / (15625_i64));
    let constant_1 = ((Float::with_val(precision, (-(53_i64)))) / (100_i64));
    let constant_2 = ((Float::with_val(precision, (-(53_i64)))) / (200_i64));
    let constant_3 = ((Float::with_val(precision, (-(53_i64)))) / (625_i64));
    let constant_4 = ((Float::with_val(precision, (-(4483_i64)))) / (125000_i64));
    let constant_5 = ((Float::with_val(precision, (-(8_i64)))) / (625_i64));
    let constant_6 = ((Float::with_val(precision, 4_i64)) / (625_i64));
    let constant_7 = ((Float::with_val(precision, 16_i64)) / (625_i64));
    let constant_8 = ((Float::with_val(precision, 8241452448849_i64)) / (244140625000000_i64));
    let constant_9 = ((Float::with_val(precision, 53_i64)) / (1250_i64));
    let constant_10 = ((Float::with_val(precision, 121_i64)) / (2500_i64));
    let constant_11 = ((Float::with_val(precision, 613_i64)) / (8000_i64));
    let constant_12 = ((Float::with_val(precision, 2_i64)) / (25_i64));
    let constant_13 = ((Float::with_val(precision, 4_i64)) / (25_i64));
    let constant_14 = ((Float::with_val(precision, 8_i64)) / (25_i64));
    let constant_15 = ((Float::with_val(precision, 517_i64)) / (1250_i64));
    let constant_16 = ((Float::with_val(precision, 2209_i64)) / (2500_i64));
    let z_v0 = Float::with_val(precision, ((&constant_12) * (xz)));
    let z_0 = ((Float::with_val(precision, ((cz) + (&constant_2)))) - (&z_v0));
    let z_1 = Float::with_val(precision, ((&constant_13) * (yz)));
    let z_2 = ((Float::with_val(precision, ((cz) + (&constant_2)))) + (&z_v0));
    let n_v0 = ((cy) + (Float::with_val(precision, ((&constant_2) * (yz)))));
    let n_1 = ((Float::with_val(precision, ((2_i64) * (cx))))
        + (Float::with_val(precision, ((&constant_1) * (xz)))));
    let n_2 = Float::with_val(precision, -(&n_v0));
    let m_v0 = Float::with_val(precision, ((cx) * (&constant_13)));
    let m_v1 = Float::with_val(precision, ((&constant_9) * (xz)));
    let m_v2 = (((c2) + (Float::with_val(precision, ((cz) * (&constant_1))))) + (&constant_11));
    let m_0 = (((Float::with_val(precision, -(&m_v0))) + (&m_v1)) + (&m_v2));
    let m_1 = ((Float::with_val(precision, ((cy) * (&constant_14))))
        + (Float::with_val(precision, ((&constant_3) * (yz)))));
    let m_2 = ((Float::with_val(precision, ((&m_v0) - (&m_v1)))) + (&m_v2));
    let r_v0 = Float::with_val(precision, ((2_i64) * (&z_0)));
    let r_0 = ((&m_0) - (Float::with_val(precision, z_0.square_ref())));
    let r_1 = ((&m_1) - (Float::with_val(precision, ((&r_v0) * (&z_1)))));
    let r_2 = (((Float::with_val(precision, ((&m_0) + (&m_2))))
        - (Float::with_val(precision, ((&r_v0) * (&z_2)))))
        - (Float::with_val(precision, z_1.square_ref())));
    let r_3 = ((&m_1) - ((Float::with_val(precision, ((2_i64) * (&z_1)))) * (&z_2)));
    let r_4 = ((&m_2) - (Float::with_val(precision, z_2.square_ref())));
    let w_v0 = Float::with_val(precision, yz.square_ref());
    let w_v1 = ((Float::with_val(precision, ((cx) * (&constant_13)))) * (&w_v0));
    let w_v2 = Float::with_val(precision, ((xz) * (yz)));
    let w_v3 = ((Float::with_val(precision, ((cy) * (&constant_13)))) * (&w_v2));
    let w_v4 = Float::with_val(precision, cy.square_ref());
    let w_v5 = Float::with_val(precision, ((c2) * (&w_v0)));
    let w_v6 = Float::with_val(precision, ((cz) * (yz)));
    let w_v7 = Float::with_val(precision, ((cy) * (&w_v6)));
    let w_v8 = ((((Float::with_val(precision, ((&constant_6) * (&w_v0)))) + (&w_v4)) + (&w_v5))
        - (Float::with_val(precision, ((2_i64) * (&w_v7)))));
    let w_v9 = Float::with_val(precision, xz.square_ref());
    let w_v10 = ((Float::with_val(precision, ((cx) * (&constant_14)))) * (&w_v2));
    let w_v11 = Float::with_val(precision, ((4_i64) * (cx)));
    let w_v12 = Float::with_val(precision, ((cz) * (xz)));
    let w_v13 = Float::with_val(precision, ((4_i64) * (c2)));
    let w_v14 = (((((Float::with_val(precision, ((cy) * (&w_v11))))
        - ((Float::with_val(precision, ((4_i64) * (cy)))) * (&w_v12)))
        + (Float::with_val(precision, ((&constant_7) * (&w_v2)))))
        - (Float::with_val(precision, ((&w_v11) * (&w_v6)))))
        + (Float::with_val(precision, ((&w_v13) * (&w_v2)))));
    let w_0 = (((Float::with_val(precision, -(&w_v1))) + (&w_v3)) + (&w_v8));
    let w_1 =
        ((((Float::with_val(precision, ((cy) * (&constant_14)))) * (&w_v9)) - (&w_v10)) + (&w_v14));
    let w_2 = (((((((((4_i64) * (Float::with_val(precision, cx.square_ref())))
        - ((Float::with_val(precision, ((8_i64) * (cx)))) * (&w_v12)))
        + (Float::with_val(precision, ((&constant_5) * (&w_v0)))))
        + (Float::with_val(precision, ((&constant_7) * (&w_v9)))))
        + (Float::with_val(precision, ((&w_v13) * (&w_v9)))))
        - (Float::with_val(precision, ((2_i64) * (&w_v4)))))
        - (Float::with_val(precision, ((2_i64) * (&w_v5)))))
        + (Float::with_val(precision, ((4_i64) * (&w_v7)))));
    let w_3 =
        ((((Float::with_val(precision, ((cy) * (&constant_14)))) * (&w_v9)) - (&w_v10)) - (&w_v14));
    let w_4 = ((Float::with_val(precision, ((&w_v1) - (&w_v3)))) + (&w_v8));
    let tau_v0 = Float::with_val(precision, ((&m_0) * (yz)));
    let tau_v1 = Float::with_val(precision, ((&m_1) * (yz)));
    let tau_v2 = Float::with_val(precision, ((&m_2) * (yz)));
    let tau_0 = (((Float::with_val(precision, -(&n_v0))) * (&z_0)) + (&tau_v0));
    let tau_1 = (((((Float::with_val(precision, ((2_i64) * (&m_0)))) * (xz))
        - (Float::with_val(precision, ((&n_1) * (&z_0)))))
        - (Float::with_val(precision, ((&n_v0) * (&z_1)))))
        + (&tau_v1));
    let tau_2 = (((((((Float::with_val(precision, ((2_i64) * (&m_1)))) * (xz))
        - (Float::with_val(precision, ((&n_1) * (&z_1)))))
        - (Float::with_val(precision, ((&n_2) * (&z_0)))))
        - (Float::with_val(precision, ((&n_v0) * (&z_2)))))
        - (&tau_v0))
        + (&tau_v2));
    let tau_3 = (((((Float::with_val(precision, ((2_i64) * (&m_2)))) * (xz))
        - (Float::with_val(precision, ((&n_1) * (&z_2)))))
        - (Float::with_val(precision, ((&n_2) * (&z_1)))))
        - (&tau_v1));
    let tau_4 = (((Float::with_val(precision, -(&n_2))) * (&z_2)) - (&tau_v2));
    let k_0 = Float::with_val(precision, ((&constant_4) + (&m_0)));
    let k_2 = Float::with_val(precision, ((&constant_4) + (&m_2)));
    let j_v0 = Float::with_val(precision, ((&constant_0) * (&m_0)));
    let j_v1 = Float::with_val(precision, ((&constant_0) * (&m_1)));
    let j_v2 = Float::with_val(precision, ((2_i64) * (&k_0)));
    let j_v3 = Float::with_val(precision, ((&constant_0) * (&m_2)));
    let j_0 = ((&j_v0) + (Float::with_val(precision, k_0.square_ref())));
    let j_1 = ((&j_v1) + (Float::with_val(precision, ((&j_v2) * (&m_1)))));
    let j_2 = ((((&j_v0) + (Float::with_val(precision, ((&j_v2) * (&k_2))))) + (&j_v3))
        + (Float::with_val(precision, m_1.square_ref())));
    let j_3 = ((&j_v1) + ((Float::with_val(precision, ((2_i64) * (&k_2)))) * (&m_1)));
    let j_4 = ((&j_v3) + (Float::with_val(precision, k_2.square_ref())));
    let rn_v0 = Float::with_val(precision, n_v0.square_ref());
    let rn_v1 = Float::with_val(precision, ((2_i64) * (&n_v0)));
    let rn_v2 = Float::with_val(precision, ((&n_1) * (&rn_v1)));
    let rn_v3 = Float::with_val(precision, n_1.square_ref());
    let rn_v4 = Float::with_val(precision, ((&n_2) * (&r_0)));
    let rn_v5 = Float::with_val(precision, ((2_i64) * (&n_1)));
    let rn_v6 = Float::with_val(precision, ((&n_2) * (&r_1)));
    let rn_v7 = Float::with_val(precision, n_2.square_ref());
    let rn_v8 = Float::with_val(precision, ((&n_2) * (&r_2)));
    let rn_v9 = Float::with_val(precision, ((&n_2) * (&r_3)));
    let rn_v10 = Float::with_val(precision, ((&n_2) * (&r_4)));
    let rn_0 = Float::with_val(precision, ((&r_0) * (&rn_v0)));
    let rn_1 = ((Float::with_val(precision, ((&r_0) * (&rn_v2))))
        + (Float::with_val(precision, ((&r_1) * (&rn_v0)))));
    let rn_2 = ((((Float::with_val(precision, ((&r_0) * (&rn_v3))))
        + (Float::with_val(precision, ((&r_1) * (&rn_v2)))))
        + (Float::with_val(precision, ((&r_2) * (&rn_v0)))))
        + (Float::with_val(precision, ((&rn_v1) * (&rn_v4)))));
    let rn_3 = (((((Float::with_val(precision, ((&r_1) * (&rn_v3))))
        + (Float::with_val(precision, ((&r_2) * (&rn_v2)))))
        + (Float::with_val(precision, ((&r_3) * (&rn_v0)))))
        + (Float::with_val(precision, ((&rn_v1) * (&rn_v6)))))
        + (Float::with_val(precision, ((&rn_v4) * (&rn_v5)))));
    let rn_4 = ((((((Float::with_val(precision, ((&r_0) * (&rn_v7))))
        + (Float::with_val(precision, ((&r_2) * (&rn_v3)))))
        + (Float::with_val(precision, ((&r_3) * (&rn_v2)))))
        + (Float::with_val(precision, ((&r_4) * (&rn_v0)))))
        + (Float::with_val(precision, ((&rn_v1) * (&rn_v8)))))
        + (Float::with_val(precision, ((&rn_v5) * (&rn_v6)))));
    let rn_5 = (((((Float::with_val(precision, ((&r_1) * (&rn_v7))))
        + (Float::with_val(precision, ((&r_3) * (&rn_v3)))))
        + (Float::with_val(precision, ((&r_4) * (&rn_v2)))))
        + (Float::with_val(precision, ((&rn_v1) * (&rn_v9)))))
        + (Float::with_val(precision, ((&rn_v5) * (&rn_v8)))));
    let rn_6 = ((((Float::with_val(precision, ((&r_2) * (&rn_v7))))
        + (Float::with_val(precision, ((&r_4) * (&rn_v3)))))
        + (Float::with_val(precision, ((&rn_v1) * (&rn_v10)))))
        + (Float::with_val(precision, ((&rn_v5) * (&rn_v9)))));
    let rn_7 = ((Float::with_val(precision, ((&r_3) * (&rn_v7))))
        + (Float::with_val(precision, ((&rn_v10) * (&rn_v5)))));
    let rn_8 = Float::with_val(precision, ((&r_4) * (&rn_v7)));
    let tt_v0 = Float::with_val(precision, ((2_i64) * (&tau_0)));
    let tt_v1 = Float::with_val(precision, ((2_i64) * (&tau_1)));
    let tt_v2 = Float::with_val(precision, ((2_i64) * (&tau_2)));
    let tt_0 = Float::with_val(precision, tau_0.square_ref());
    let tt_1 = Float::with_val(precision, ((&tau_1) * (&tt_v0)));
    let tt_2 = ((Float::with_val(precision, tau_1.square_ref()))
        + (Float::with_val(precision, ((&tau_2) * (&tt_v0)))));
    let tt_3 = ((Float::with_val(precision, ((&tau_2) * (&tt_v1))))
        + (Float::with_val(precision, ((&tau_3) * (&tt_v0)))));
    let tt_4 = (((Float::with_val(precision, tau_2.square_ref()))
        + (Float::with_val(precision, ((&tau_3) * (&tt_v1)))))
        + (Float::with_val(precision, ((&tau_4) * (&tt_v0)))));
    let tt_5 = ((Float::with_val(precision, ((&tau_3) * (&tt_v2))))
        + (Float::with_val(precision, ((&tau_4) * (&tt_v1)))));
    let tt_6 = ((Float::with_val(precision, tau_3.square_ref()))
        + (Float::with_val(precision, ((&tau_4) * (&tt_v2)))));
    let tt_7 = ((Float::with_val(precision, ((2_i64) * (&tau_3)))) * (&tau_4));
    let tt_8 = Float::with_val(precision, tau_4.square_ref());
    let e_0 = (((Float::with_val(precision, ((&constant_10) * (&tt_0))))
        + (Float::with_val(precision, ((&constant_16) * (&rn_0)))))
        + (Float::with_val(precision, ((&j_0) * (&w_0)))));
    let e_1 = ((((Float::with_val(precision, ((&constant_10) * (&tt_1))))
        + (Float::with_val(precision, ((&constant_16) * (&rn_1)))))
        + (Float::with_val(precision, ((&j_0) * (&w_1)))))
        + (Float::with_val(precision, ((&j_1) * (&w_0)))));
    let e_2 = (((((Float::with_val(precision, ((&constant_10) * (&tt_2))))
        + (Float::with_val(precision, ((&constant_16) * (&rn_2)))))
        + (Float::with_val(precision, ((&j_0) * (&w_2)))))
        + (Float::with_val(precision, ((&j_1) * (&w_1)))))
        + (Float::with_val(precision, ((&j_2) * (&w_0)))));
    let e_3 = ((((((Float::with_val(precision, ((&constant_10) * (&tt_3))))
        + (Float::with_val(precision, ((&constant_16) * (&rn_3)))))
        + (Float::with_val(precision, ((&j_0) * (&w_3)))))
        + (Float::with_val(precision, ((&j_1) * (&w_2)))))
        + (Float::with_val(precision, ((&j_2) * (&w_1)))))
        + (Float::with_val(precision, ((&j_3) * (&w_0)))));
    let e_4 = (((((((Float::with_val(precision, ((&constant_10) * (&tt_4))))
        + (Float::with_val(precision, ((&constant_16) * (&rn_4)))))
        + (Float::with_val(precision, ((&j_0) * (&w_4)))))
        + (Float::with_val(precision, ((&j_1) * (&w_3)))))
        + (Float::with_val(precision, ((&j_2) * (&w_2)))))
        + (Float::with_val(precision, ((&j_3) * (&w_1)))))
        + (Float::with_val(precision, ((&j_4) * (&w_0)))));
    let e_5 = ((((((Float::with_val(precision, ((&constant_10) * (&tt_5))))
        + (Float::with_val(precision, ((&constant_16) * (&rn_5)))))
        + (Float::with_val(precision, ((&j_1) * (&w_4)))))
        + (Float::with_val(precision, ((&j_2) * (&w_3)))))
        + (Float::with_val(precision, ((&j_3) * (&w_2)))))
        + (Float::with_val(precision, ((&j_4) * (&w_1)))));
    let e_6 = (((((Float::with_val(precision, ((&constant_10) * (&tt_6))))
        + (Float::with_val(precision, ((&constant_16) * (&rn_6)))))
        + (Float::with_val(precision, ((&j_2) * (&w_4)))))
        + (Float::with_val(precision, ((&j_3) * (&w_3)))))
        + (Float::with_val(precision, ((&j_4) * (&w_2)))));
    let e_7 = ((((Float::with_val(precision, ((&constant_10) * (&tt_7))))
        + (Float::with_val(precision, ((&constant_16) * (&rn_7)))))
        + (Float::with_val(precision, ((&j_3) * (&w_4)))))
        + (Float::with_val(precision, ((&j_4) * (&w_3)))));
    let e_8 = (((Float::with_val(precision, ((&constant_10) * (&tt_8))))
        + (Float::with_val(precision, ((&constant_16) * (&rn_8)))))
        + (Float::with_val(precision, ((&j_4) * (&w_4)))));
    let o_v0 = Float::with_val(precision, ((&constant_15) * (&tau_0)));
    let o_v1 = Float::with_val(precision, ((&constant_15) * (&tau_1)));
    let o_v2 = Float::with_val(precision, ((&constant_15) * (&tau_2)));
    let o_v3 = Float::with_val(precision, ((&constant_15) * (&tau_3)));
    let o_v4 = Float::with_val(precision, ((&constant_15) * (&tau_4)));
    let o_0 = Float::with_val(precision, ((&n_v0) * (&o_v0)));
    let o_1 = ((Float::with_val(precision, ((&n_1) * (&o_v0))))
        + (Float::with_val(precision, ((&n_v0) * (&o_v1)))));
    let o_2 = (((Float::with_val(precision, ((&n_1) * (&o_v1))))
        + (Float::with_val(precision, ((&n_2) * (&o_v0)))))
        + (Float::with_val(precision, ((&n_v0) * (&o_v2)))));
    let o_3 = (((Float::with_val(precision, ((&n_1) * (&o_v2))))
        + (Float::with_val(precision, ((&n_2) * (&o_v1)))))
        + (Float::with_val(precision, ((&n_v0) * (&o_v3)))));
    let o_4 = (((Float::with_val(precision, ((&n_1) * (&o_v3))))
        + (Float::with_val(precision, ((&n_2) * (&o_v2)))))
        + (Float::with_val(precision, ((&n_v0) * (&o_v4)))));
    let o_5 = ((Float::with_val(precision, ((&n_1) * (&o_v4))))
        + (Float::with_val(precision, ((&n_2) * (&o_v3)))));
    let o_6 = Float::with_val(precision, ((&n_2) * (&o_v4)));
    let oo_v0 = Float::with_val(precision, ((2_i64) * (&o_0)));
    let oo_v1 = Float::with_val(precision, ((2_i64) * (&o_1)));
    let oo_v2 = Float::with_val(precision, ((2_i64) * (&o_2)));
    let oo_v3 = Float::with_val(precision, ((2_i64) * (&o_3)));
    let oo_v4 = Float::with_val(precision, ((2_i64) * (&o_4)));
    let oo_0 = Float::with_val(precision, o_0.square_ref());
    let oo_1 = Float::with_val(precision, ((&o_1) * (&oo_v0)));
    let oo_2 = ((Float::with_val(precision, o_1.square_ref()))
        + (Float::with_val(precision, ((&o_2) * (&oo_v0)))));
    let oo_3 = ((Float::with_val(precision, ((&o_2) * (&oo_v1))))
        + (Float::with_val(precision, ((&o_3) * (&oo_v0)))));
    let oo_4 = (((Float::with_val(precision, o_2.square_ref()))
        + (Float::with_val(precision, ((&o_3) * (&oo_v1)))))
        + (Float::with_val(precision, ((&o_4) * (&oo_v0)))));
    let oo_5 = (((Float::with_val(precision, ((&o_3) * (&oo_v2))))
        + (Float::with_val(precision, ((&o_4) * (&oo_v1)))))
        + (Float::with_val(precision, ((&o_5) * (&oo_v0)))));
    let oo_6 = ((((Float::with_val(precision, o_3.square_ref()))
        + (Float::with_val(precision, ((&o_4) * (&oo_v2)))))
        + (Float::with_val(precision, ((&o_5) * (&oo_v1)))))
        + (Float::with_val(precision, ((&o_6) * (&oo_v0)))));
    let oo_7 = (((Float::with_val(precision, ((&o_4) * (&oo_v3))))
        + (Float::with_val(precision, ((&o_5) * (&oo_v2)))))
        + (Float::with_val(precision, ((&o_6) * (&oo_v1)))));
    let oo_8 = (((Float::with_val(precision, o_4.square_ref()))
        + (Float::with_val(precision, ((&o_5) * (&oo_v3)))))
        + (Float::with_val(precision, ((&o_6) * (&oo_v2)))));
    let oo_9 = ((Float::with_val(precision, ((&o_5) * (&oo_v4))))
        + (Float::with_val(precision, ((&o_6) * (&oo_v3)))));
    let oo_10 = ((Float::with_val(precision, o_5.square_ref()))
        + (Float::with_val(precision, ((&o_6) * (&oo_v4)))));
    let oo_11 = ((Float::with_val(precision, ((2_i64) * (&o_5)))) * (&o_6));
    let oo_12 = Float::with_val(precision, o_6.square_ref());
    let u_0 = ((Float::with_val(precision, e_0.square_ref()))
        - (Float::with_val(precision, ((&oo_0) * (&r_0)))));
    let u_1 = ((((Float::with_val(precision, ((2_i64) * (&e_0)))) * (&e_1))
        - (Float::with_val(precision, ((&oo_0) * (&r_1)))))
        - (Float::with_val(precision, ((&oo_1) * (&r_0)))));
    let u_2 = ((((((Float::with_val(precision, ((2_i64) * (&e_0)))) * (&e_2))
        + (Float::with_val(precision, e_1.square_ref())))
        - (Float::with_val(precision, ((&oo_0) * (&r_2)))))
        - (Float::with_val(precision, ((&oo_1) * (&r_1)))))
        - (Float::with_val(precision, ((&oo_2) * (&r_0)))));
    let u_3 = (((((((Float::with_val(precision, ((2_i64) * (&e_0)))) * (&e_3))
        + ((Float::with_val(precision, ((2_i64) * (&e_1)))) * (&e_2)))
        - (Float::with_val(precision, ((&oo_0) * (&r_3)))))
        - (Float::with_val(precision, ((&oo_1) * (&r_2)))))
        - (Float::with_val(precision, ((&oo_2) * (&r_1)))))
        - (Float::with_val(precision, ((&oo_3) * (&r_0)))));
    let u_4 = (((((((((Float::with_val(precision, ((2_i64) * (&e_0)))) * (&e_4))
        + ((Float::with_val(precision, ((2_i64) * (&e_1)))) * (&e_3)))
        + (Float::with_val(precision, e_2.square_ref())))
        - (Float::with_val(precision, ((&oo_0) * (&r_4)))))
        - (Float::with_val(precision, ((&oo_1) * (&r_3)))))
        - (Float::with_val(precision, ((&oo_2) * (&r_2)))))
        - (Float::with_val(precision, ((&oo_3) * (&r_1)))))
        - (Float::with_val(precision, ((&oo_4) * (&r_0)))));
    let u_5 = (((((((((Float::with_val(precision, ((2_i64) * (&e_0)))) * (&e_5))
        + ((Float::with_val(precision, ((2_i64) * (&e_1)))) * (&e_4)))
        + ((Float::with_val(precision, ((2_i64) * (&e_2)))) * (&e_3)))
        - (Float::with_val(precision, ((&oo_1) * (&r_4)))))
        - (Float::with_val(precision, ((&oo_2) * (&r_3)))))
        - (Float::with_val(precision, ((&oo_3) * (&r_2)))))
        - (Float::with_val(precision, ((&oo_4) * (&r_1)))))
        - (Float::with_val(precision, ((&oo_5) * (&r_0)))));
    let u_6 = ((((((((((Float::with_val(precision, ((2_i64) * (&e_0)))) * (&e_6))
        + ((Float::with_val(precision, ((2_i64) * (&e_1)))) * (&e_5)))
        + ((Float::with_val(precision, ((2_i64) * (&e_2)))) * (&e_4)))
        + (Float::with_val(precision, e_3.square_ref())))
        - (Float::with_val(precision, ((&oo_2) * (&r_4)))))
        - (Float::with_val(precision, ((&oo_3) * (&r_3)))))
        - (Float::with_val(precision, ((&oo_4) * (&r_2)))))
        - (Float::with_val(precision, ((&oo_5) * (&r_1)))))
        - (Float::with_val(precision, ((&oo_6) * (&r_0)))));
    let u_7 = ((((((((((Float::with_val(precision, ((2_i64) * (&e_0)))) * (&e_7))
        + ((Float::with_val(precision, ((2_i64) * (&e_1)))) * (&e_6)))
        + ((Float::with_val(precision, ((2_i64) * (&e_2)))) * (&e_5)))
        + ((Float::with_val(precision, ((2_i64) * (&e_3)))) * (&e_4)))
        - (Float::with_val(precision, ((&oo_3) * (&r_4)))))
        - (Float::with_val(precision, ((&oo_4) * (&r_3)))))
        - (Float::with_val(precision, ((&oo_5) * (&r_2)))))
        - (Float::with_val(precision, ((&oo_6) * (&r_1)))))
        - (Float::with_val(precision, ((&oo_7) * (&r_0)))));
    let u_8 = (((((((((((Float::with_val(precision, ((2_i64) * (&e_0)))) * (&e_8))
        + ((Float::with_val(precision, ((2_i64) * (&e_1)))) * (&e_7)))
        + ((Float::with_val(precision, ((2_i64) * (&e_2)))) * (&e_6)))
        + ((Float::with_val(precision, ((2_i64) * (&e_3)))) * (&e_5)))
        + (Float::with_val(precision, e_4.square_ref())))
        - (Float::with_val(precision, ((&oo_4) * (&r_4)))))
        - (Float::with_val(precision, ((&oo_5) * (&r_3)))))
        - (Float::with_val(precision, ((&oo_6) * (&r_2)))))
        - (Float::with_val(precision, ((&oo_7) * (&r_1)))))
        - (Float::with_val(precision, ((&oo_8) * (&r_0)))));
    let u_9 = ((((((((((Float::with_val(precision, ((2_i64) * (&e_1)))) * (&e_8))
        + ((Float::with_val(precision, ((2_i64) * (&e_2)))) * (&e_7)))
        + ((Float::with_val(precision, ((2_i64) * (&e_3)))) * (&e_6)))
        + ((Float::with_val(precision, ((2_i64) * (&e_4)))) * (&e_5)))
        - (Float::with_val(precision, ((&oo_5) * (&r_4)))))
        - (Float::with_val(precision, ((&oo_6) * (&r_3)))))
        - (Float::with_val(precision, ((&oo_7) * (&r_2)))))
        - (Float::with_val(precision, ((&oo_8) * (&r_1)))))
        - (Float::with_val(precision, ((&oo_9) * (&r_0)))));
    let u_10 = ((((((((((Float::with_val(precision, ((2_i64) * (&e_2)))) * (&e_8))
        + ((Float::with_val(precision, ((2_i64) * (&e_3)))) * (&e_7)))
        + ((Float::with_val(precision, ((2_i64) * (&e_4)))) * (&e_6)))
        + (Float::with_val(precision, e_5.square_ref())))
        - (Float::with_val(precision, ((&oo_10) * (&r_0)))))
        - (Float::with_val(precision, ((&oo_6) * (&r_4)))))
        - (Float::with_val(precision, ((&oo_7) * (&r_3)))))
        - (Float::with_val(precision, ((&oo_8) * (&r_2)))))
        - (Float::with_val(precision, ((&oo_9) * (&r_1)))));
    let u_11 = (((((((((Float::with_val(precision, ((2_i64) * (&e_3)))) * (&e_8))
        + ((Float::with_val(precision, ((2_i64) * (&e_4)))) * (&e_7)))
        + ((Float::with_val(precision, ((2_i64) * (&e_5)))) * (&e_6)))
        - (Float::with_val(precision, ((&oo_10) * (&r_1)))))
        - (Float::with_val(precision, ((&oo_11) * (&r_0)))))
        - (Float::with_val(precision, ((&oo_7) * (&r_4)))))
        - (Float::with_val(precision, ((&oo_8) * (&r_3)))))
        - (Float::with_val(precision, ((&oo_9) * (&r_2)))));
    let u_12 = (((((((((Float::with_val(precision, ((2_i64) * (&e_4)))) * (&e_8))
        + ((Float::with_val(precision, ((2_i64) * (&e_5)))) * (&e_7)))
        + (Float::with_val(precision, e_6.square_ref())))
        - (Float::with_val(precision, ((&oo_10) * (&r_2)))))
        - (Float::with_val(precision, ((&oo_11) * (&r_1)))))
        - (Float::with_val(precision, ((&oo_12) * (&r_0)))))
        - (Float::with_val(precision, ((&oo_8) * (&r_4)))))
        - (Float::with_val(precision, ((&oo_9) * (&r_3)))));
    let u_13 = (((((((Float::with_val(precision, ((2_i64) * (&e_5)))) * (&e_8))
        + ((Float::with_val(precision, ((2_i64) * (&e_6)))) * (&e_7)))
        - (Float::with_val(precision, ((&oo_10) * (&r_3)))))
        - (Float::with_val(precision, ((&oo_11) * (&r_2)))))
        - (Float::with_val(precision, ((&oo_12) * (&r_1)))))
        - (Float::with_val(precision, ((&oo_9) * (&r_4)))));
    let u_14 = ((((((Float::with_val(precision, ((2_i64) * (&e_6)))) * (&e_8))
        + (Float::with_val(precision, e_7.square_ref())))
        - (Float::with_val(precision, ((&oo_10) * (&r_4)))))
        - (Float::with_val(precision, ((&oo_11) * (&r_3)))))
        - (Float::with_val(precision, ((&oo_12) * (&r_2)))));
    let u_15 = ((((Float::with_val(precision, ((2_i64) * (&e_7)))) * (&e_8))
        - (Float::with_val(precision, ((&oo_11) * (&r_4)))))
        - (Float::with_val(precision, ((&oo_12) * (&r_3)))));
    let u_16 = ((Float::with_val(precision, e_8.square_ref()))
        - (Float::with_val(precision, ((&oo_12) * (&r_4)))));
    vec![
        Float::with_val(precision, ((&constant_8) * (&u_0))),
        Float::with_val(precision, ((&constant_8) * (&u_1))),
        Float::with_val(precision, ((&constant_8) * (&u_2))),
        Float::with_val(precision, ((&constant_8) * (&u_3))),
        Float::with_val(precision, ((&constant_8) * (&u_4))),
        Float::with_val(precision, ((&constant_8) * (&u_5))),
        Float::with_val(precision, ((&constant_8) * (&u_6))),
        Float::with_val(precision, ((&constant_8) * (&u_7))),
        Float::with_val(precision, ((&constant_8) * (&u_8))),
        Float::with_val(precision, ((&constant_8) * (&u_9))),
        Float::with_val(precision, ((&constant_8) * (&u_10))),
        Float::with_val(precision, ((&constant_8) * (&u_11))),
        Float::with_val(precision, ((&constant_8) * (&u_12))),
        Float::with_val(precision, ((&constant_8) * (&u_13))),
        Float::with_val(precision, ((&constant_8) * (&u_14))),
        Float::with_val(precision, ((&constant_8) * (&u_15))),
        Float::with_val(precision, ((&constant_8) * (&u_16))),
    ]
}

/// Parse the shortest decimal representation, as Python mp.mpf(str(float(v))) does.
fn decimal_float(value: f64, precision: u32) -> Float {
    Float::with_val(
        precision,
        Float::parse(value.to_string()).expect("finite decimal"),
    )
}

fn dot(a: &[Float; 3], b: &[Float; 3], precision: u32) -> Float {
    let mut result = Float::with_val(precision, &a[0] * &b[0]);
    result += Float::with_val(precision, &a[1] * &b[1]);
    result += Float::with_val(precision, &a[2] * &b[2]);
    result
}

/// Evaluate the polynomial for a pose expressed in the DH6 frame.
///
/// The quaternion is [w, x, y, z]. It is renormalized at the requested precision
/// before computing pose invariants; this preserves the rotation identities used
/// by the polynomial elimination. Callers must supply a finite nonzero quaternion.
pub fn coefficients_from_pose(
    position: [f64; 3],
    quat_wxyz: [f64; 4],
    precision: u32,
) -> Vec<Float> {
    let mut quaternion = quat_wxyz.map(|value| decimal_float(value, precision));
    let mut norm = Float::with_val(precision, 0);
    for value in &quaternion {
        norm += Float::with_val(precision, value.square_ref());
    }
    norm.sqrt_mut();
    assert!(!norm.is_zero() && norm.is_finite(), "invalid quaternion");
    for value in &mut quaternion {
        *value /= &norm;
    }
    let [qw, qx, qy, qz] = &quaternion;
    let xx = Float::with_val(precision, qx.square_ref());
    let yy = Float::with_val(precision, qy.square_ref());
    let zz = Float::with_val(precision, qz.square_ref());
    let xy = Float::with_val(precision, qx * qy);
    let xz = Float::with_val(precision, qx * qz);
    let yz = Float::with_val(precision, qy * qz);
    let wx = Float::with_val(precision, qw * qx);
    let wy = Float::with_val(precision, qw * qy);
    let wz = Float::with_val(precision, qw * qz);
    let xd = [
        Float::with_val(precision, 1) - Float::with_val(precision, &yy + &zz) * 2,
        Float::with_val(precision, &xy + &wz) * 2,
        Float::with_val(precision, &xz - &wy) * 2,
    ];
    let yd = [
        Float::with_val(precision, &xy - &wz) * 2,
        Float::with_val(precision, 1) - Float::with_val(precision, &xx + &zz) * 2,
        Float::with_val(precision, &yz + &wx) * 2,
    ];
    let zd = [
        Float::with_val(precision, &xz + &wy) * 2,
        Float::with_val(precision, &yz - &wx) * 2,
        Float::with_val(precision, 1) - Float::with_val(precision, &xx + &yy) * 2,
    ];
    let d6 = Float::with_val(precision, 101) / 1000;
    let c = std::array::from_fn(|i| {
        decimal_float(position[i], precision) - Float::with_val(precision, &d6 * &zd[i])
    });
    let invariants = [
        dot(&c, &c, precision),
        dot(&c, &xd, precision),
        dot(&c, &yd, precision),
        c[2].clone(),
        xd[2].clone(),
        yd[2].clone(),
    ];
    coefficients_from_invariants(&invariants, precision)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn parse(value: &str, precision: u32) -> Float {
        Float::with_val(precision, Float::parse(value).unwrap())
    }

    fn assert_relative(actual: &Float, expected: &Float, tolerance: &Float) {
        let error = Float::with_val(actual.prec(), actual - expected).abs();
        let bound = Float::with_val(actual.prec(), expected.clone().abs() * tolerance);
        assert!(
            error <= bound,
            "actual={actual}, expected={expected}, error={error}"
        );
    }

    #[test]
    fn known_invariants_match_python_at_two_precisions() {
        // Generated independently with mpmath at 100 decimal digits.
        let expected = [
            "0.000000287847191724094839207279541523162105818229243904",
            "-0.000002584880248891474894894828331678831176396050530304",
            "0.000008257709227382985901863332874376018085219615637504",
            "-0.000014157705552160933114844924842447501015061152923648",
            "0.000021503949321119426946617096752025681599485088628736",
            "-0.00002544099033766683619054052597208422676189432250368",
            "0.000014405483078261169127778259184887470653028173873152",
            "-0.000013471694525925064427767415212452828563748144807936",
            "-0.000001105117502399762299886923980931886313093073993728",
            "0.000011671353123469628959320209860372459463902878498816",
            "0.000007466377513967725487909124940766390504622403878912",
            "0.0000195809480994712822601339169314620765316912775168",
            "0.000016136857591611027056618159060281362222266849427456",
            "0.000010603334347818875369794170327865964201781963522048",
            "0.000006951190031792957288042874932978401267649687322624",
            "0.000002297179206828817316082590765400881953676055281664",
            "0.000000256913685727798955833651311837654569771360845824",
        ];
        for (precision, tolerance) in [(128, "1e-30"), (256, "1e-65")] {
            let values =
                ["0.45", "0.1", "-0.2", "0.5", "0.3", "-0.4"].map(|value| parse(value, precision));
            let coefficients = coefficients_from_invariants(&values, precision);
            for (actual, expected) in coefficients.iter().zip(expected) {
                assert_relative(
                    actual,
                    &parse(expected, precision),
                    &parse(tolerance, precision),
                );
            }
        }
    }

    #[test]
    fn identity_pose_matches_analytic_invariants() {
        let precision = 256;
        let values =
            ["0.289201", "0.2", "-0.3", "0.399", "0", "0"].map(|value| parse(value, precision));
        let expected = coefficients_from_invariants(&values, precision);
        let actual = coefficients_from_pose([0.2, -0.3, 0.5], [1.0, 0.0, 0.0, 0.0], precision);
        for (actual, expected) in actual.iter().zip(&expected) {
            assert_relative(actual, expected, &parse("1e-68", precision));
        }
    }

    #[test]
    fn quaternion_rescaling_preserves_coefficients() {
        let precision = 256;
        let actual = coefficients_from_pose([0.2, -0.3, 0.5], [2.0, -4.0, 6.0, -8.0], precision);
        let expected = coefficients_from_pose([0.2, -0.3, 0.5], [1.0, -2.0, 3.0, -4.0], precision);
        for (actual, expected) in actual.iter().zip(&expected) {
            assert_relative(actual, expected, &parse("1e-68", precision));
        }
    }
}
