import {geometricJacobian,geometry,compileExpression,checkExpression,zeroContours,customCriticalCurves,customDeterminant,slicePosition,solveSliceIK,checkRegionPair} from './exercise-03-math.js';
import {customPosition,sliceConfiguration,analyzeCustomPath,DEFAULT_CUSTOM_PATH,CUSTOM_CUSP} from '../viz/lecture07CustomMath.js';
import {createCustomURDFViewer} from '../viz/lecture07CustomViewer.js';
const $=selector=>document.querySelector(selector),$$=selector=>[...document.querySelectorAll(selector)],PI=Math.PI,KEY='eng654.exercise03.v1',NS='http://www.w3.org/2000/svg';
const state={answers:{},checks:{},q:[.3,-.6,1],selected:null,mapPoint:null,probes:[],activeProbe:-1,loop:null,loopBranch:0,frame:0,playing:false};
const matrix=$('#jacobian-inputs'),grid=document.createElement('div');grid.className='ex03-matrix';grid.innerHTML='<span></span><strong>Joint 1</strong><strong>Joint 2</strong><strong>Joint 3</strong>';
for(let r=0;r<6;r++){const label=document.createElement('span');label.textContent=['vₓ','vᵧ','v_z','ωₓ','ωᵧ','ω_z'][r];grid.append(label);for(let c=0;c<3;c++){const field=document.createElement('label');field.className='ex03-field';const input=document.createElement('input');input.type='text';input.maxLength=500;input.dataset.answer=`J.${r+1}.${c+1}`;input.setAttribute('aria-label',`Jacobian row ${r+1} column ${c+1}`);input.autocomplete='off';input.spellcheck=false;field.append(input);const feedback=document.createElement('small');feedback.className='answer-feedback';field.append(feedback);grid.append(field);}}matrix.append(grid);
const bonusGrid=document.createElement('div');bonusGrid.className='ex03-matrix ex03-bonus-matrix';bonusGrid.innerHTML='<span></span>'+Array.from({length:6},(_,i)=>`<strong>Joint ${i+1}</strong>`).join('');
for(let r=0;r<6;r++){
 const label=document.createElement('span');label.textContent=['vₓ','vᵧ','v_z','ωₓ','ωᵧ','ω_z'][r];bonusGrid.append(label);
 for(let c=0;c<6;c++){
  const field=document.createElement('label');field.className='ex03-field';const input=document.createElement('input');input.type='text';input.maxLength=500;input.dataset.answer=`bonus.J.${r+1}.${c+1}`;
  input.setAttribute('aria-label',`Bonus Jacobian expressed in frame 3 at O4, row ${r+1} (${['linear x','linear y','linear z','angular x','angular y','angular z'][r]}), column ${c+1} (joint ${c+1})`);input.setAttribute('aria-describedby','bonus-matrix-help');input.autocomplete='off';input.spellcheck=false;field.append(input);bonusGrid.append(field);
 }
}
$('#bonus-jacobian-inputs').append(bonusGrid);
const bonusFields=$$('[data-answer^="bonus.J."]'),known=new Set($$('[data-answer]').map(el=>el.dataset.answer));
function reviewBonus(){
 const derivation=$('[data-answer="bonus.crb-jacobian"]'),written=!!derivation.value.trim(),filled=bonusFields.filter(field=>field.value.trim()).length;
 for(const field of [...bonusFields,derivation]){if(field.value.trim())field.dataset.result='review';else field.removeAttribute('data-result');}
 derivation.closest('.ex03-field').querySelector('.answer-feedback').textContent=written?'Recorded for instructor review; this derivation is not automatically graded.':'';
 $('#bonus-status').textContent=filled||written?`Bonus saved · ${filled}/36 matrix entries · ${written?'derivation included':'add your derivation'} · instructor review; not automatically graded.`:'Optional · no bonus response entered · instructor review';
}
function status(message,error=false){$('#file-status').textContent=message;$('#file-status').classList.toggle('answer-status-error',error);}
function documentValue(){return {schemaVersion:1,exercise:'exercise_03',model:'custom_3R',units:{length:'m',angle:'rad'},answers:{...state.answers},investigation:{probes:state.probes.map(probe=>probe.source==='joint'?{source:'joint',q:probe.q.slice()}:{source:'workspace',point:probe.point.slice()})}};}
function save(){try{localStorage.setItem(KEY,JSON.stringify(documentValue()));}catch{status('Browser storage unavailable. Download responses to save your work.');}}
function setAnswer(key,value){state.answers[key]=String(value);$$('[data-answer]').filter(el=>el.dataset.answer===key).forEach(el=>{if(el.type==='radio')el.checked=el.value===String(value);else el.value=value;el.removeAttribute('data-result');});save();}
function feedback(key,result){const fields=$$('[data-answer]').filter(el=>el.dataset.answer===key),wrap=fields[0]?.closest('.ex03-field,.ex03-choice');fields.forEach(el=>el.dataset.result=result.correct?'correct':'incorrect');if(wrap?.classList.contains('ex03-choice'))wrap.dataset.result=result.correct?'correct':'incorrect';const note=wrap?.querySelector('.answer-feedback');if(note)note.textContent=result.message;state.checks[key]=result.correct;return result.correct;}
const choices={separation:'critical-preimage',cuspidality:'nonsingular-change','four-to-two':'pair-disappears','two-to-four':'pair-appears','workspace-boundary':'critical-preimages','cusp-joint':'tangent-preimage','fold-roots':'2','cusp-roots':'3'};
function checkChoice(key){return feedback(key,{correct:state.answers[key]===choices[key],message:state.answers[key]===choices[key]?'Correct.':'Reconsider the geometry and the branch continuation.'});}
function check(stage){let good=0,total=0;
 if(stage==='jacobian'){for(let r=0;r<6;r++)for(let c=0;c<3;c++){const key=`J.${r+1}.${c+1}`;good+=feedback(key,checkExpression(state.answers[key]||'',q=>geometricJacobian(q)[r][c]));total++;}}
 if(stage==='determinant'){good=+feedback('determinant',checkExpression(state.answers.determinant||'',q=>customDeterminant(q.slice(1))));total=1;}
 if(stage==='separation'){const pair=checkRegionPair(state.answers);for(const key of ['a2','a3','b2','b3'])feedback(`region.${key}`,pair);good=+pair.correct+checkChoice('separation');total=2;state.checks.region=pair.correct;const note=$('[data-answer="separation.explanation"]');note.dataset.result=note.value.trim()?'review':'incorrect';$('[data-status="separation"]').textContent=pair.message+' Written interpretation: instructor review.';return good===total;}
 if(stage==='boundaries'){good=['workspace-boundary','cusp-joint','fold-roots','cusp-roots'].filter(checkChoice).length;total=4;}
 if(stage==='cuspidality'){good=+checkChoice('cuspidality');total=1;}
 if(stage==='transitions'){good=+checkChoice('four-to-two')+checkChoice('two-to-four');total=2;}
 const target=$(`[data-status="${stage}"]`);if(target)target.textContent=`${good}/${total} checks passed.`;return good===total;
}
function checkAll(){const stages=['jacobian','determinant','separation','boundaries','cuspidality','transitions'],passed=stages.filter(check).length;reviewBonus();$('#progress').textContent=`${passed}/6 sections checked successfully`;status(`${passed}/6 sections checked successfully. Written explanations and the bonus are retained for instructor review.`);return passed;}
function importDocument(value){if(!value||value.schemaVersion!==1||value.exercise!=='exercise_03'||!value.answers||typeof value.answers!=='object'||Array.isArray(value.answers))throw Error('Choose an Exercise 03 response JSON with schemaVersion 1.');const entries=Object.entries(value.answers);if(entries.length>80)throw Error('Too many answer fields.');const clean={};for(const [key,answer] of entries){if(!known.has(key))continue;if(typeof answer!=='string'&&typeof answer!=='number')throw Error(`Invalid answer type for ${key}.`);if(String(answer).length>(key.endsWith('explanation')||key==='bonus.crb-jacobian'?4000:500))throw Error(`Answer ${key} is too long.`);clean[key]=String(answer);}const probes=validateProbes(value.investigation?.probes||[]);state.probes=probes;state.activeProbe=probes.length-1;state.selected=null;state.mapPoint=null;if(probes.length){const last=probes.at(-1);state.mapPoint=last.point;state.selected=last.source==='joint'?last.q:last.roots[0]||null;}state.answers={};$$('[data-answer]').forEach(el=>{if(el.type==='radio')el.checked=false;else el.value='';el.removeAttribute('data-result');});state.checks={};for(const [key,answer] of Object.entries(clean))setAnswer(key,answer);save();checkAll();drawMaps();if(state.answers.determinant)plotExpression();}
$$('[data-answer]').forEach(el=>el.addEventListener('input',()=>{if(el.type!=='radio'||el.checked)state.answers[el.dataset.answer]=el.value;el.removeAttribute('data-result');const group=el.closest('.ex03-choice,.ex03-field');group?.removeAttribute('data-result');if(group?.querySelector('.answer-feedback'))group.querySelector('.answer-feedback').textContent='';delete state.checks[el.dataset.answer];if(el.dataset.answer.startsWith('bonus.'))$('#bonus-status').textContent='Bonus changed · saved with your responses · instructor review';$('#progress').textContent='Responses changed · check again';save();}));
$$('[data-check]').forEach(button=>button.addEventListener('click',()=>check(button.dataset.check)));$('#check-all').addEventListener('click',checkAll);
$('#download-responses').addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(documentValue(),null,2)+'\n'],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='exercise_03_responses.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);status('Downloaded your current Exercise 03 responses.');});
$('#load-responses').addEventListener('change',async event=>{const file=event.target.files[0];if(!file)return;try{if(file.size>1000000)throw Error('The response file must be smaller than 1 MB.');importDocument(JSON.parse(await file.text()));status('Responses loaded and checked. Written explanations remain for instructor review.');}catch(error){status(`Could not load responses: ${error.message}`,true);}finally{event.target.value='';}});
// Small SVG plots retain sharp axes, labels and curves at any display resolution.
function svgNode(tag,attrs={},text){const el=document.createElementNS(NS,tag);for(const [k,v] of Object.entries(attrs))el.setAttribute(k,v);if(text!==undefined)el.textContent=text;return el;}
let nextPlot=0;
function makePlot(selector,{joint=false,bounds=joint?[[-PI,PI],[-PI,PI]]:[[0,5],[-3,5]],onPoint}={}){const svg=$(selector+' svg'),id='ex03-clip-'+(++nextPlot),width=620,height=440,box={x:60,y:24,w:535,h:356};let model={};svg.setAttribute('viewBox',`0 0 ${width} ${height}`);const px=p=>[box.x+(p[0]-bounds[0][0])/(bounds[0][1]-bounds[0][0])*box.w,box.y+(bounds[1][1]-p[1])/(bounds[1][1]-bounds[1][0])*box.h];
 function render(next={}){model=next;svg.replaceChildren();const defs=svgNode('defs'),clip=svgNode('clipPath',{id});clip.append(svgNode('rect',{x:box.x,y:box.y,width:box.w,height:box.h}));defs.append(clip);svg.append(defs);const area=svgNode('g',{'clip-path':`url(#${id})`});svg.append(area);area.append(svgNode('rect',{x:box.x,y:box.y,width:box.w,height:box.h,fill:model.allZero?'#f3f3f3':'white'}));
  const ticks=joint?[-PI,-PI/2,0,PI/2,PI]:null;
  for(let axis=0;axis<2;axis++){const values=ticks||Array.from({length:6},(_,i)=>bounds[axis][0]+i*(bounds[axis][1]-bounds[axis][0])/5);values.forEach((v,i)=>{const p=px(axis===0?[v,bounds[1][0]]:[bounds[0][0],v]);area.append(svgNode('line',axis===0?{x1:p[0],x2:p[0],y1:box.y,y2:box.y+box.h,stroke:'#b9c1c7','stroke-opacity':'.45'}:{x1:box.x,x2:box.x+box.w,y1:p[1],y2:p[1],stroke:'#b9c1c7','stroke-opacity':'.45'}));svg.append(svgNode('text',axis===0?{x:p[0],y:box.y+box.h+23,'text-anchor':'middle','font-size':14}:{x:box.x-9,y:p[1]+5,'text-anchor':'end','font-size':14},joint?['−π','−π/2','0','π/2','π'][i]:String(+v.toFixed(2))));});}
  function lines(points){if(!joint)return [points];const result=[];let line=[];for(const p of points){if(line.length&&p.some((x,i)=>Math.abs(x-line.at(-1)[i])>PI)){result.push(line);line=[];}line.push(p);}if(line.length)result.push(line);return result;}
  for(const layer of model.layers||[]){const paths=(layer.lines||[]).flatMap(lines),d=paths.map(line=>line.map((p,i)=>`${i?'L':'M'}${px(p).map(v=>v.toFixed(2)).join(',')}`).join('')).join('');area.append(svgNode('path',{d,fill:'none',stroke:layer.color||'#b33227','stroke-width':layer.width||1.6,'stroke-dasharray':layer.dash||'none','stroke-linejoin':'round','data-layer':layer.name||'curve'}));}
  const textPositions=[];
  for(const layer of model.dots||[])layer.points.forEach((p,i)=>{const [cx,cy]=px(p);area.append(svgNode('circle',{cx,cy,r:layer.r||2,fill:layer.color||'#111',stroke:layer.stroke||'none','stroke-width':layer.stroke?1.3:0,...(layer.name?{'data-point-layer':layer.name}:{}),...(layer.labels?{'data-point-label':layer.labels[i]}:{})}));if(layer.labels){const label=layer.labels[i],labelWidth=Math.max(9,String(label).length*7),offsets=[[7,-7],[7,17],[-labelWidth-7,-7],[-labelWidth-7,17],[7,31],[-labelWidth-7,-21]];let position;for(const [dx,dy] of offsets){const candidate={x:Math.max(box.x+2,Math.min(box.x+box.w-labelWidth-2,cx+dx)),y:Math.max(box.y+12,Math.min(box.y+box.h-3,cy+dy)),w:labelWidth};if(!textPositions.some(p=>candidate.x<p.x+p.w+3&&candidate.x+candidate.w+3>p.x&&Math.abs(candidate.y-p.y)<15)){position=candidate;break;}}position||={x:cx+7,y:cy-7,w:labelWidth};textPositions.push(position);area.append(svgNode('text',{x:position.x,y:position.y,'font-size':12,'font-weight':700,fill:'#111',stroke:'white','stroke-width':3,'paint-order':'stroke'},label));}});
  svg.append(svgNode('rect',{x:box.x,y:box.y,width:box.w,height:box.h,fill:'none',stroke:'#6f777c'}),svgNode('text',{x:box.x+box.w/2,y:425,'text-anchor':'middle','font-size':17,'font-weight':700},joint?'q₂ [rad]':'ρ [m]'),svgNode('text',{transform:`translate(19 ${box.y+box.h/2}) rotate(-90)`,'text-anchor':'middle','font-size':17,'font-weight':700},joint?'q₃ [rad]':'z [m]'));svg.dataset.segmentCount=String((model.layers||[]).reduce((s,l)=>s+(l.lines||[]).length,0));
 }
 svg.addEventListener('click',event=>{if(!onPoint)return;const point=svg.createSVGPoint();point.x=event.clientX;point.y=event.clientY;const p=point.matrixTransform(svg.getScreenCTM().inverse());if(p.x<box.x||p.x>box.x+box.w||p.y<box.y||p.y>box.y+box.h)return;onPoint([bounds[0][0]+(p.x-box.x)/box.w*(bounds[0][1]-bounds[0][0]),bounds[1][1]-(p.y-box.y)/box.h*(bounds[1][1]-bounds[1][0])]);});render();return {render};}
const expressionPlot=makePlot('#expression-plot',{joint:true});
function plotExpression(){const message=$('#expression-status');try{const fn=compileExpression(state.answers.determinant||'');message.textContent='Locating zeros of your expression…';const result=zeroContours(fn,{n:+$('#plot-resolution').value});expressionPlot.render({layers:[{lines:result.segments,name:'student-zero-set'}],allZero:result.allZero});message.textContent=result.allZero?'Your expression is zero everywhere: its zero set is the whole plot.':`${result.segments.length} contour segments from your expression.${result.invalid?' Undefined samples were skipped; discontinuities are not zeros.':''}${!result.segments.length?' No zeros resolved on this grid.':''}`;$('#expression-plot').dataset.source=state.answers.determinant||'';return result;}catch(error){expressionPlot.render();message.textContent=`Cannot plot: ${error.message}`;return null;}}
$('#plot-expression').addEventListener('click',plotExpression);$('#plot-resolution').addEventListener('change',()=>{if(state.answers.determinant)plotExpression();});
const modelViewer=createCustomURDFViewer($('#model-scene'),{compactOpacity:true});
function updateRobot(){modelViewer.update(state.q);const geo=geometry(state.q),table=document.createElement('table');table.className='ex03-table';table.innerHTML='<thead><tr><th>i</th><th>World axis direction</th><th>World point on axis [m]</th></tr></thead>';const body=document.createElement('tbody');for(let i=0;i<3;i++){const tr=document.createElement('tr');for(const value of [String(i+1),geo.axes[i].map(v=>v.toFixed(4)).join(', '),geo.origins[i].map(v=>v.toFixed(4)).join(', ')]){const td=document.createElement('td');td.textContent=value;tr.append(td);}body.append(tr);}table.append(body);$('#geometry-table').replaceChildren(table);}
for(let i=0;i<3;i++){const label=document.createElement('label');label.innerHTML=`<span>q${i+1}</span><input type="range" min="-180" max="180" step="1" value="${state.q[i]*180/PI}" aria-label="Model joint ${i+1}"><output>${(state.q[i]*180/PI).toFixed(0)}°</output>`;label.querySelector('input').addEventListener('input',event=>{state.q[i]=+event.target.value*PI/180;label.querySelector('output').textContent=event.target.value+'°';updateRobot();});$('#robot-joints').append(label);}updateRobot();
let reference=null;
const jointPlot=makePlot('#joint-map',{joint:true,onPoint:q=>selectJoint(q)}),workspacePlot=makePlot('#workspace-map',{onPoint:p=>selectWorkspace(p)});
function makeProbe(source,coordinates){
 if(!Array.isArray(coordinates)||coordinates.length!==2||!coordinates.every(Number.isFinite))throw Error('Each recorded sample needs two finite coordinates.');
 if(source==='joint'){if(coordinates.some(q=>Math.abs(q)>PI+1e-10))throw Error('Joint samples must stay within [−π, π].');const q=coordinates.slice(),point=slicePosition(q);return {source,q,point,roots:[]};}
 if(source!=='workspace'||coordinates[0]<0||coordinates[0]>5||coordinates[1]<-3||coordinates[1]>5)throw Error('Workspace samples must lie within the displayed axes.');
 const point=coordinates.slice();return {source,point,roots:solveSliceIK(point),continuous:point[0]<1e-9};
}
function validateProbes(probes){if(!Array.isArray(probes)||probes.length>200)throw Error('A response file may contain up to 200 recorded samples.');return probes.map(probe=>{if(!probe||typeof probe!=='object')throw Error('Invalid recorded sample.');return makeProbe(probe.source,probe.source==='joint'?probe.q:probe.point);});}
function drawMaps(){if(!reference)return;const showSingular=$('#show-singular').checked,current=state.probes[state.activeProbe],jointDots=[],workspaceDots=[];
 state.probes.forEach((probe,i)=>{const active=i===state.activeProbe,points=probe.source==='joint'?[probe.q]:probe.roots,label=String(i+1);jointDots.push({points,labels:points.map((_,j)=>probe.source==='joint'?label:label+String.fromCharCode(97+j)),r:active?4.5:3.5,color:active?'#111':'white',stroke:'#111',name:'investigation'});workspaceDots.push({points:[probe.point],labels:[label],r:active?4.5:3.5,color:active?'#111':'white',stroke:'#111',name:'investigation'});});
 if(state.selected&&current?.source==='workspace')jointDots.push({points:[state.selected],r:7,color:'none',stroke:'#111',name:'selection'});
 jointPlot.render({layers:showSingular?[{lines:reference.joint,name:'singular'}]:[],dots:jointDots});workspacePlot.render({layers:showSingular?[{lines:reference.workspace,name:'critical'}]:[],dots:workspaceDots});
 $('#map-status').textContent=current?`Sample ${state.activeProbe+1} · ${current.source==='joint'?'FK from your joint configuration':'IK from your workspace point'}: ρ = ${current.point[0].toFixed(4)} m, z = ${current.point[1].toFixed(4)} m; ${current.source==='joint'?'click this position in the workspace plot to enumerate its IKs':current.continuous&&current.roots.length?'continuous IK family (q₁ is free); '+current.roots.length+' reduced (q₂, q₃) solutions':current.roots.length+' distinct IKs'}.${state.selected?` Selected (q₂, q₃) = (${state.selected.map(q=>q.toFixed(4)).join(', ')}) rad; det Jₚ = ${customDeterminant(state.selected).toFixed(5)}.`:''}`:'Click either plot to begin your investigation.';
 $('#point-history').replaceChildren();state.probes.forEach((probe,i)=>{const button=document.createElement('button');button.type='button';button.textContent=`${i+1} · ${probe.source==='joint'?'FK':'IK'}`;button.setAttribute('aria-pressed',String(i===state.activeProbe));button.addEventListener('click',()=>activateProbe(i));$('#point-history').append(button);});
 $('#ik-buttons').replaceChildren();if(current?.source==='workspace')current.roots.forEach((q,i)=>{const button=document.createElement('button');button.type='button';button.textContent=`IK ${state.activeProbe+1}${String.fromCharCode(97+i)} · (${q.map(v=>v.toFixed(2)).join(', ')})`;button.setAttribute('aria-pressed',String(!!state.selected&&Math.hypot(...q.map((x,k)=>Math.atan2(Math.sin(x-state.selected[k]),Math.cos(x-state.selected[k]))))<1e-5));button.addEventListener('click',()=>{state.selected=q.slice();drawMaps();});$('#ik-buttons').append(button);});
 for(const selector of ['#joint-map','#workspace-map']){const host=$(selector);if(current?.source==='workspace')host.dataset.ikCount=current.continuous&&current.roots.length?'continuous':String(current.roots.length);else delete host.dataset.ikCount;host.dataset.sampleCount=String(state.probes.length);}$('#clear-points').disabled=!state.probes.length;
}
function activateProbe(index){const probe=state.probes[index];if(!probe)return;state.activeProbe=index;state.mapPoint=probe.point;state.selected=probe.source==='joint'?probe.q:probe.roots[0]||null;drawMaps();}
function recordProbe(source,coordinates){try{if(state.probes.length>=200)throw Error('You have recorded 200 samples. Download your work, then erase the plotted points to start another investigation.');state.probes.push(makeProbe(source,coordinates));activateProbe(state.probes.length-1);save();}catch(error){status(error.message,true);}}
function selectJoint(q){recordProbe('joint',q);}
function selectWorkspace(p){recordProbe('workspace',p);}
function clearPoints(){state.probes=[];state.activeProbe=-1;state.selected=null;state.mapPoint=null;drawMaps();save();}
$('#show-singular').addEventListener('change',drawMaps);$('#clear-points').addEventListener('click',clearPoints);
$$('[data-record]').forEach(button=>button.addEventListener('click',()=>{if(!state.selected){status('Select an available joint configuration on the map first.',true);return;}const prefix=button.dataset.record;setAnswer(`region.${prefix}2`,state.selected[0].toFixed(8));setAnswer(`region.${prefix}3`,state.selected[1].toFixed(8));status(`Recorded the selected joint configuration as ${prefix.toUpperCase()}.`);}));
setTimeout(()=>{reference=customCriticalCurves(600);drawMaps();document.body.dataset.exerciseReady='true';},20);
$('#record-bonus').addEventListener('click',()=>{reviewBonus();save();});
const loopWork=makePlot('#loop-workspace',{bounds:[[2.05,3.15],[2.35,3.65]]}),loopJoint=makePlot('#loop-joint',{joint:true});let loopViewer=null,lastFrameTime=0;
function renderLoop(){const analysis=state.loop;if(!analysis)return;const track=analysis.tracks[state.loopBranch],index=Math.min(state.frame,track.path.length-1),q=track.path[index],closed=track.closure<1e-5;loopViewer.update(sliceConfiguration(q));loopWork.render({layers:[{lines:reference?.workspace||[]},{lines:[analysis.workspace],color:'#777',dash:'5 4'},{lines:[track.reached.slice(0,index+1)],color:'#111',width:3}],dots:[{points:[CUSTOM_CUSP],r:3,color:'#b33227'},{points:[track.reached[index]],r:5,color:'#111'}]});loopJoint.render({layers:[{lines:reference?.joint||[]},{lines:[track.path.slice(0,index+1)],color:'#111',width:3}],dots:[{points:[track.path[0]],r:4,color:'#fff',stroke:'#111'},{points:[q],r:5,color:'#111'}]});$('#loop-status').textContent=`IK${state.loopBranch+1}: ${track.success?(closed?'complete · joint loop closes':'complete · nonsingular change to a different IK'):track.reason} Minimum |det Jₚ| = ${track.minDet.toPrecision(4)}. Sample ${index+1}/${track.path.length}. ${analysis.starts.length} starting IKs: ${analysis.regular.length} closed, ${analysis.nonsingular.length} nonsingular change, ${analysis.infeasible.length} stop.`;$('#loop-scene').dataset.completed=String(index===track.path.length-1);}
function resetLoop(){state.playing=false;state.frame=0;$('#play-loop').textContent='Play';const track=state.loop?.tracks[state.loopBranch];if(track){loopViewer.setGhost(sliceConfiguration(track.path[0]));loopViewer.setTrace(state.loop.workspace);renderLoop();}}
function animate(time){if(!state.playing)return;const track=state.loop.tracks[state.loopBranch];if(time-lastFrameTime>=30){state.frame=Math.min(state.frame+3,track.path.length-1);lastFrameTime=time;renderLoop();}if(state.frame===track.path.length-1){state.playing=false;$('#play-loop').textContent='Replay';return;}requestAnimationFrame(animate);}
$('#analyse-loop').addEventListener('click',()=>{state.loop=analyzeCustomPath(DEFAULT_CUSTOM_PATH,.008);if(!loopViewer)loopViewer=createCustomURDFViewer($('#loop-scene'),{compactOpacity:true});const select=$('#loop-branch');select.replaceChildren();state.loop.tracks.forEach((track,i)=>{const option=document.createElement('option');option.value=i;option.textContent=`IK${i+1}`;select.append(option);});state.loopBranch=0;select.disabled=false;$('#play-loop').disabled=false;$('#reset-loop').disabled=false;resetLoop();});
$('#loop-branch').addEventListener('change',event=>{state.loopBranch=+event.target.value;resetLoop();});$('#reset-loop').addEventListener('click',resetLoop);$('#play-loop').addEventListener('click',()=>{if(!state.loop)return;if(state.playing){state.playing=false;$('#play-loop').textContent='Play';return;}const track=state.loop.tracks[state.loopBranch];if(state.frame>=track.path.length-1)state.frame=0;state.playing=true;lastFrameTime=0;$('#play-loop').textContent='Pause';requestAnimationFrame(animate);});
try{const stored=localStorage.getItem(KEY);if(stored)importDocument(JSON.parse(stored));}catch(error){status('Saved data could not be restored: '+error.message,true);}
window.Exercise03={document:documentValue,importDocument,checkAll,plotExpression,selectJoint,selectWorkspace,clearPoints,snapshot:()=>({document:documentValue(),checks:{...state.checks},selected:state.selected,probes:state.probes.map(probe=>({source:probe.source,point:probe.point,q:probe.q,roots:probe.roots})),activeProbe:state.activeProbe,loop:state.loop&&{starts:state.loop.starts.length,closed:state.loop.regular.length,nonsingular:state.loop.nonsingular.length,stopped:state.loop.infeasible.length},frame:state.frame,playing:state.playing})};
